### ISSUE TITLE
fix animate back to value

### ISSUE THREAD

**Issue by steipete** [pascalw/PDColoredProgressview#2]
currently, if animated=YES and targetProgress is LOWER than set progress, it doesn't do anything at all. 

to fix, replace movieProgress with
- (void) moveProgress {
  if (self.progress < _targetProgress) {
    self.progress = MIN(self.progress + 0.01, _targetProgress);
  }
  else if(self.progress > _targetProgress) {
    self.progress = MAX(self.progress - 0.01, _targetProgress);  
  }else {
    [_progressTimer invalidate];
    _progressTimer = nil;
  }
  }

(too lazy to fork and send pull request.. sry)

**Comment by pascalw** [comment]
Fix for #2, closed by bedc596f767ee32cf1ff1c5ff09db69231cd45b5. Updated gitignore to exclude some XCode 4 files.

**Comment by steipete** [comment]
thanks!
