### ISSUE TITLE
No color change with iOS5 beta 1

### ISSUE THREAD

**Issue by sylverb** [pascalw/PDColoredProgressview#3]
Hello,
when using PDColoredProgressview on iOS 5 beta 1, all the progress bars are staying in the blue color ...
Note that it may be a bug in iOS 5 beta 1 as everything seems right in your code ...

**Comment by pascalw** [comment]
Hi,
thanks for the heads up. I'll keep an eye on it in next beta's.

I've taken a look at the new API docs and it seems that there has been some API changes regarding UIProgressView. I'll add IOS 5 compatibility soon, when beta's get a little bit more stable.

**Comment by constantine-fry** [comment]
in iOS5 UIProgressView does not use drawRect: anymore
i modify setTintColor method and its working:
- (void) setTintColor: (UIColor *) aColor {
  if ([self respondsToSelector:@selector(progressTintColor)]) {
      self.progressTintColor = aColor;
  }else{
      [_tintColor release];
      _tintColor = [aColor retain];
  }
  }

**Comment by sylverb** [comment]
Nice !
To make it compatible with iOS4 SDK, use
 [self setProgressTintColor:aColor];
instead of
 self.progressTintColor = aColor; !

**Comment by pascalw** [comment]
I think it's to early to implement IOS 5 compatibility now so I'll just wait a bit until IOS 5 API's are stable.
